### ISSUE TITLE
looking for wrong version

### ISSUE THREAD

**Issue by festro** [dphaldes/Ars-Ocultas#1]
not sure if it's a typo in the dependencies but this mod is looking for Ars Nouveau 4.3.0 when the latest version (that I know of) is 4.2.4 which causes the game to crash on load.

**Comment by dphaldes** [comment]
4.3.0 is the current development version yet to be released. It's undergoing a lot of testing. Please wait :)

**Comment by festro** [comment]
Ok thanks for the clarification.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dphaldes** [comment]
I have made a new release which targets older version for now since NeoForge will take some time :) 
https://legacy.curseforge.com/minecraft/mc-mods/ars-ocultas/files/4732736

**Comment by festro** [comment]
Thank you.
