### ISSUE TITLE
Modrinth latest 1.20.1 version depends on "Unknown Project"

### ISSUE THREAD

**Issue by PinkDisorder** [dphaldes/Ars-Ocultas#4]
As the title says, [Ars Ocultas 1.20.1-1.2.2](https://modrinth.com/mod/ars-ocultas/version/1.20.1-1.2.2) has "Unknown Project" listed as a required dependency, which makes it impossible to pull in the mod via the Prism Launcher.

**Comment by dphaldes** [comment]
Fixed! Thanks for informing!
